---
title: "Hathaway, de Genovia à Gotham."
author: "Mateus de Lima Oliveira"
date: "13 de maio de 2019"
output:
  html_document:
    code_folding: "hide"
    toc: yes
    toc_depth: 5
    toc_float:
      collapsed: no
    df_print: paged
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
theme_set(theme_bw())
library(boot)
library(broom)
options(scipen = 999)
knitr::opts_chunk$set(tidy = FALSE,
                      fig.width = 6,
                      fig.height = 5)
```

```{r read}
titanic = read_csv(here::here("data/train.csv"), 
                 col_types = "dddccdddcdcc") 
startups = read_csv(here::here("data/50_Startups.csv"),
                 col_types = "dddcd")

titanic
startups

```


### Plots


```{r}
startups %>%
    summarise(pearson = cor(Marketing, Profit, method = "pearson"))
    
startups %>%
    ggplot(aes(x = Marketing, y = Profit))+
    geom_point(aes( size = ReD, alpha = 0.4))+
    labs(title = "Correlação entre Lucro e gasto com Marketing",
       y = "Lucro", x = "Marketing",
       caption = "Fonte: vozes da minha cabeça")

```

